[pytest]
markers =
    smoke: mark test as smoke
    regression: mark test as regression
    sanity: mark test as sanity
    ddt: mark test as data-driven testing
    login: mark test as login related
    search: mark test as search related
